# Generated by Django 5.0.6 on 2024-07-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_middlena_me_item_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agency_employee_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='blood_type',
            field=models.CharField(default='O', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='citizenship',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='item',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='fathers_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='gsis_id_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='height_m',
            field=models.DecimalField(decimal_places=2, default=1.75, max_digits=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='mobile_no',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='mothers_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='pagibig_id_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='permanent_address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='philhealth_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='residential_address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='sss_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='telephone_no',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='tin_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='item',
            name='zip_code',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
