# Generated by Django 5.0.6 on 2024-07-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_agency_employee_no_alter_item_blood_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fathers_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='agency_employee_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gsis_id_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height_m',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mothers_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pagibig_id_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='philhealth_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='residential_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sss_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='telephone_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tin_no',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.CharField(default='Unknown College', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary',
            field=models.CharField(default='Unknown Elementary', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='item',
            name='father_first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='father_middle_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_middle_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='occupation',
            field=models.CharField(default='Unemployed', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='item',
            name='secondary',
            field=models.CharField(default='Unknown High School', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='blood_type',
            field=models.CharField(default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='civil_status',
            field=models.CharField(default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='Edcel', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.CharField(default='Capuyan', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(default='Aspera', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
