# Generated by Django 5.0.6 on 2024-07-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_fathers_name_item_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='first_name',
            field=models.CharField(default='Iverson', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_name',
            field=models.CharField(default='Sulbiano', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='middle_name',
            field=models.CharField(default='Delfin', max_length=100),
        ),
    ]
